- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "{{ my_var }}"
    - name: Clone hello-world-war repo
      git:
        repo: https://github.com/dwillington/hello-world-war.git
        dest: /tmp/