- name: Deploy JBoss
  hosts: all
  tasks:
    - name: Capture my_var from Jenkins
      debug:
        msg: "{{ my_var }}"
    #https://www.unixarena.com/2018/12/ansible-tower-awx-store-credential-custom-credentials-type.html/
    - name: Capture Jenkins_password as new Credential Type
      debug:
        msg: "{{ Jenkins_password }}"
    - name: secret stuff
      command: "hg clone -u https://user:{{ Jenkins_password }}@host/path"
      # no_log: true
    - name: Clone hello-world-war repo
      git:
        repo: https://github.com/dwillington/hello-world-war.git
        dest: /tmp/hello-world-war
    # - name: Download deployment artifact from Artifactory
      # maven_artifact:
        # group_id: "{{ group_id }}"              # com.tu
        # artifact_id: "{{ artifact_id }}"        # c2_online
        # version: latest
        # dest: /tmp/{{ artifact_id }}.jar
        # repository_url: "{{ repository_url }}"  # http://artifactory.transunion.ca/snapshots
        # username: user
        # password: pass
