agent: 'master' # This will be the default agent

workflow:
  - branch: 'master' 
    steps: 
      - notification:
          stage_name: 'INITIAL SCM NOTIFICATION'
          checkout_scm: true
          clean_up_workspace: false
          notification_type: 'SCM'
          in_progress: true
      - maven:
          stage_name: 'MAVEN BUILD'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'BUILD'
          maven_command: 'mvn clean install'
      - notification:
          stage_name: 'EMAIL NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: false
          notification_type: 'EMAIL'
          notification_email_sender: dwillington@yahoo.com'
          notification_email_recipients: dwillington@yahoo.com'
      - notification:
          stage_name: 'FINAL SCM NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: true
          notification_type: 'SCM'
          in_progress: false