agent: 'master' # This will be the default agent

workflow:
  - branch: 'master' 
    steps: 
      - notification:
          stage_name: 'INITIAL SCM NOTIFICATION'
          checkout_scm: true
          clean_up_workspace: false
          notification_type: 'PUBLISH_REPORT'
          in_progress: true
      - maven:
          stage_name: 'MAVEN BUILD'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'BUILD'
          maven_command: 'mvn clean install'
      - notification:
          stage_name: 'EMAIL NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: false
          notification_type: 'EMAIL'
          notification_email_sender: dwillington@yahoo.com'
          notification_email_recipients: dwillington@yahoo.com'
      - notification:
          stage_name: 'FINAL SCM NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: true
          notification_type: 'SCM'
          in_progress: false

  - branch: 'develop'
    steps: 
      - notification:
          stage_name: 'INITIAL SCM NOTIFICATION'
          checkout_scm: true
          clean_up_workspace: false
          notification_type: 'SCM'
          in_progress: true
      - maven:
          stage_name: 'MAVEN BUILD'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'BUILD'
          maven_command: 'mvn clean install'
      - scan:
          stage_name: 'SONARQUBE SCAN'
          checkout_scm: false
          clean_up_workspace: false
          scan_type: 'SONARQUBE'
          sonarqube_strategy: 'MAVEN'
      - scan:
          stage_name: 'SONATYPE SCAN'
          checkout_scm: false
          clean_up_workspace: false
          scan_type: 'SONATYPE'
          sonatype_application_id: 'CFP'
      - scan:
          stage_name: 'VERACODE SCAN'
          checkout_scm: false
          clean_up_workspace: false
          scan_type: 'VERACODE'
          veracode_application_id: 'TDCT - Credit Fulfillment Platform'
          veracode_sandbox_id: 'com.td.cfp.api'
          veracode_upload_pattern: '**/target/**.war' 
          veracode_wait_for_completion: false
      - maven:
          stage_name: 'MAVEN PUBLISH'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'PUBLISH'
          maven_command: 'mvn deploy -DskipTests -B'  
          version_strategy: 'PATCH'              
      #- deploy:
          #stage_name: 'JBOSS DEPLOY - DEV'
          #checkout_scm: false
          #clean_up_workspace: false
          #deploy_type: 'JBOSS'
          #deployment_env: 'DEV'
          #deployment_target: '10.106.176.189'
          #deployment_artifact: 'target/com.td.cfp.api.war'
      - notification:
          stage_name: 'EMAIL NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: false
          notification_type: 'EMAIL'
          notification_email_sender: dwillington@yahoo.com'
          notification_email_recipients: dwillington@yahoo.com'
      - notification:
          stage_name: 'FINAL SCM NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: true
          notification_type: 'SCM'
          in_progress: false

  - branch: 'release'
    steps:
      - notification:
          stage_name: 'INITIAL SCM NOTIFICATION'
          checkout_scm: true
          clean_up_workspace: false
          notification_type: 'SCM'
          in_progress: true          
      - maven:
          stage_name: 'MAVEN BUILD'
          checkout_scm: false
          clean_up_workspace: false
          maven_operation_type: 'BUILD'
          maven_command: 'mvn clean deploy -P jar-build'          
      - utility:
          stage_name: 'COAPP UI'
          checkout_scm: false
          clean_up_workspace: false
          utility_type: 'RUN_JENKINS_JOB'
          job_path: '/COAPP/UI/release%2F19.march'
          job_parameter_map: ""
          #job_parameter_map: "[[$class: 'StringParameterValue', name: 'GIT_BRANCH', value: 'release/19.march'], [$class: 'StringParameterValue', name: 'ANGULAR_VERSION', value: 'RELEASE'], [$class: 'StringParameterValue', name: 'ARTIFACT_ID', value: 'release/19.march']]"
          job_wait_for_completion: true          
      - scan:
          stage_name: 'SONARQUBE SCAN'
          checkout_scm: false
          clean_up_workspace: false
          scan_type: 'SONARQUBE'
          sonarqube_strategy: 'MAVEN'          
      #- deploy:
          #stage_name: 'JBOSS DEPLOY - DEV'
          #checkout_scm: false
          #clean_up_workspace: false
          #deploy_type: 'JBOSS'
          #deployment_env: 'DEV'
          #deployment_target: '10.155.57.96'
          #deployment_artifact: 'target/hoj-ui-war-1.0-SNAPSHOT.war'          
      # - maven: 
          # stage_name: 'MAVEN RELEASE'
          # checkout_scm: false
          # clean_up_workspace: false
          # maven_operation_type: 'RELEASE'
          # maven_command: 'mvn -B release:prepare release:perform -Darguments="-Dmaven.javadoc.skip=true"'     
          # version_strategy: 'PATCH'
      - notification:
          stage_name: 'EMAIL NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: false
          notification_type: 'EMAIL'
          notification_email_sender: dwillington@yahoo.com'
          notification_email_recipients: dwillington@yahoo.com'          
      - notification:
          stage_name: 'FINAL SCM NOTIFICATION'
          checkout_scm: false
          clean_up_workspace: true
          notification_type: 'SCM'
          in_progress: false