CREATE DATABASE OPTIMIZEDPRICE;
CREATE TABLE OPTIMIZEDPRICE.PRODUCTPRICES 
   (           PRODUCT_ID VARCHAR(255 ), 
               STORE_ID VARCHAR(255 ), 
               AVAILABILITYMSG VARCHAR(4000 ), 
               REGPRICE DOUBLE(30,8), 
               PROMOPRICE DOUBLE(30,8), 
               WASPRICE DOUBLE(30,8), 
               PRICESOURCE VARCHAR(255 ), 
               SOFDPRICE DOUBLE(30,8), 
               PRICEMSG VARCHAR(255 ), 
               PRODUCTSTATUS VARCHAR(255 ), 
               PROMOENABLED VARCHAR(255 ), 
               COMPARABLEREGPRICE DOUBLE(30,8), 
               COMPARABLEREGUNITOFMEASURE VARCHAR(255 ), 
               COMPARABLEPROMOPRICE DOUBLE(30,8), 
               COMPARABLEPROMOUNITOFMEASURE VARCHAR(255 ), 
               COMPARABLEWASPRICE DOUBLE(30,8), 
               COMPARABLEWASUNITOFMEASURE VARCHAR(255 )
   );
CREATE UNIQUE INDEX i_prodauto_tod_idx1 ON OPTIMIZEDPRICE . PRODUCTPRICES (PRODUCT_ID,STORE_ID) USING BTREE;

CREATE DATABASE hybrisdbuser;
CREATE USER 'hybrisdbuser'@'%' IDENTIFIED BY 'jasp3r91';
GRANT ALL PRIVILEGES ON *.* TO 'hybrisdbuser'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW VARIABLES LIKE 'innodb_flush_log_at_trx_commit';
SET GLOBAL innodb_flush_log_at_trx_commit  = 0;
