job('maven-sample-develop') 
{
    scm 
    {
        git
        {
            remote
            {
                 branch('develop')
                 url('https://github.com/dwillington/myrepo.git')
                 credentials('git-dwillington-repo')
            }
        }
    }
    triggers 
    {
        scm('*/15 * * * *')
    }
    steps 
    {
        maven
		{
            goals('-e clean deploy')
            localRepository(LocalRepositoryLocation.LOCAL_TO_WORKSPACE)
            rootPOM('maven-projects/sample/pom.xml')
            mavenInstallation('apache-maven-3.3.9')
        }
    }
}